<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="OM" failures="1" tests="1" name="Test2" time="39.506" errors="0" timestamp="2025-02-03T14:46:56 IST">
  <testcase classname="testCases.TC002_LoginTest" name="verify_login" time="20.327">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC002_LoginTest.verify_login(TC002_LoginTest.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- verify_login -->
</testsuite> <!-- Test2 -->
